"""
Django settings for dropshipping project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import sys
from urllib.parse import parse_qs, unquote, urlparse
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def _to_bool(value, default=False):
    """Parse environment booleans safely without raising."""
    if value is None:
        return default
    if isinstance(value, bool):
        return value

    normalized = str(value).strip().lower()
    if normalized in {'1', 'true', 'yes', 'on', 'y', 't', 'debug', 'development'}:
        return True
    if normalized in {'0', 'false', 'no', 'off', 'n', 'f', 'prod', 'production', 'release'}:
        return False
    return default


def _csv_to_list(value):
    if not value:
        return []
    return [item.strip() for item in str(value).split(',') if item.strip()]


def _is_local_host(host):
    normalized = (host or '').strip().lower()
    if not normalized:
        return True
    if ':' in normalized:
        normalized = normalized.split(':', 1)[0]
    return normalized in {'localhost', '127.0.0.1', 'testserver'}


def _read_config(name, default=''):
    return str(config(name, default=default)).strip()


def _env_or_config(name, default=''):
    # Process env wins over .env values if present.
    if name in os.environ:
        return str(os.environ.get(name, '')).strip()
    return _read_config(name, default)


RENDER_EXTERNAL_HOSTNAME = str(os.getenv('RENDER_EXTERNAL_HOSTNAME', '')).strip()
_BASE_DIR_POSIX = str(BASE_DIR).replace('\\', '/')
RENDER_PATH_HINT = _BASE_DIR_POSIX.startswith('/opt/render/project/')
RUNNING_ON_RENDER = (
    _to_bool(os.getenv('RENDER', 'False'), default=False)
    or bool(RENDER_EXTERNAL_HOSTNAME)
    or bool(str(os.getenv('RENDER_SERVICE_ID', '')).strip())
    or bool(str(os.getenv('RENDER_INSTANCE_ID', '')).strip())
    or RENDER_PATH_HINT
)


def _db_value(name, default=''):
    """
    Use runtime environment values when present; otherwise fallback to .env.
    """
    return _env_or_config(name, default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_raw_secret_key = _env_or_config('SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _to_bool(_env_or_config('DEBUG', 'True'), default=True)
if RUNNING_ON_RENDER:
    # Never default to DEBUG=True on hosted runtime.
    DEBUG = _to_bool(os.getenv('DEBUG', 'False'), default=False)

if _raw_secret_key:
    SECRET_KEY = _raw_secret_key
elif DEBUG:
    # Per-process secret for local development when SECRET_KEY is not set.
    SECRET_KEY = get_random_secret_key()
else:
    raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG is False.')

ALLOWED_HOSTS = _csv_to_list(_env_or_config('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver'))
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

IS_PRODUCTION = _to_bool(_env_or_config('DJANGO_PRODUCTION', 'False'), default=False)
if not IS_PRODUCTION and not DEBUG:
    IS_PRODUCTION = any(not _is_local_host(host) for host in ALLOWED_HOSTS)

if IS_PRODUCTION and (SECRET_KEY.startswith('django-insecure-') or len(SECRET_KEY) < 50):
    raise ImproperlyConfigured('Use a strong, non-default SECRET_KEY when running in production.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django.contrib.sites',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'crispy_forms',
    # 'crispy_bootstrap5',
    # 'phonenumber_field',
    # 'django_extensions',
    # 'django_filters',
    
    # Local apps
    'core',
    'accounts',
    'products',
    'orders',
    'sellers',
    'cart',
    'reviews',
    'payments',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.DynamicCSRFMiddleware',
]

ROOT_URLCONF = 'dropshipping.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'core.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'dropshipping.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Priority:
# 1) DATABASE_URL (common on Render/Railway/Heroku)
# 2) DB_ENGINE + DB_NAME + DB_USER + DB_PASSWORD + DB_HOST + DB_PORT
# 3) Local SQLite fallback for development
DATABASE_URL = _db_value('DATABASE_URL', '')
if not DATABASE_URL:
    DATABASE_URL = _db_value('POSTGRES_URL', '')
if not DATABASE_URL:
    DATABASE_URL = _db_value('POSTGRESQL_URL', '')

RAW_DB_ENGINE = _db_value('DB_ENGINE', '')
DB_ENGINE_ALIASES = {
    'sqlite3': 'django.db.backends.sqlite3',
    'postgres': 'django.db.backends.postgresql',
    'postgresql': 'django.db.backends.postgresql',
    'mysql': 'django.db.backends.mysql',
}
DB_ENGINE = DB_ENGINE_ALIASES.get(RAW_DB_ENGINE, RAW_DB_ENGINE)

if DATABASE_URL:
    parsed = urlparse(DATABASE_URL)
    scheme = (parsed.scheme or '').lower()

    if scheme in {'postgres', 'postgresql'}:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': unquote((parsed.path or '').lstrip('/')),
                'USER': unquote(parsed.username or ''),
                'PASSWORD': unquote(parsed.password or ''),
                'HOST': parsed.hostname or '',
                'PORT': str(parsed.port or ''),
            }
        }

        query_params = parse_qs(parsed.query or '')
        ssl_mode = (query_params.get('sslmode') or [''])[0]
        if ssl_mode:
            DATABASES['default']['OPTIONS'] = {'sslmode': ssl_mode}
    elif scheme in {'sqlite', 'sqlite3'}:
        sqlite_path = unquote((parsed.path or '').lstrip('/'))
        sqlite_name = sqlite_path if os.path.isabs(sqlite_path) else str(BASE_DIR / sqlite_path)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': sqlite_name,
            }
        }
    else:
        raise ImproperlyConfigured(f"Unsupported DATABASE_URL scheme: '{scheme}'")
elif DB_ENGINE:
    default_db_name = str(BASE_DIR / 'db.sqlite3') if DB_ENGINE == 'django.db.backends.sqlite3' else ''
    db_name = _db_value('DB_NAME', '') or _db_value('PGDATABASE', default_db_name)
    db_user = _db_value('DB_USER', '') or _db_value('PGUSER', '')
    db_password = _db_value('DB_PASSWORD', '') or _db_value('PGPASSWORD', '')
    db_host = _db_value('DB_HOST', '') or _db_value('PGHOST', '')
    db_port = _db_value('DB_PORT', '') or _db_value('PGPORT', '5432')

    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': db_name,
        }
    }
    if DB_ENGINE != 'django.db.backends.sqlite3':
        DATABASES['default'].update({
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
        })
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

if IS_PRODUCTION and DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    raise ImproperlyConfigured(
        'SQLite is not supported in production. Configure PostgreSQL with DATABASE_URL or DB_* variables.'
    )

CURRENT_COMMAND = sys.argv[1] if len(sys.argv) > 1 else ''
SKIP_DB_GUARD_COMMANDS = {'collectstatic'}

if (
    RUNNING_ON_RENDER
    and DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql'
    and CURRENT_COMMAND not in SKIP_DB_GUARD_COMMANDS
):
    db_host = (DATABASES['default'].get('HOST') or '').strip()
    if _is_local_host(db_host):
        raise ImproperlyConfigured(
            'Render runtime is trying to use localhost PostgreSQL. Set DATABASE_URL from your Render PostgreSQL service.'
        )


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_METADATA_CLASS': 'core.drf_metadata.EmptyMetadata',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('DRF_THROTTLE_ANON', default='120/min'),
        'user': config('DRF_THROTTLE_USER', default='240/min'),
    },
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Django Allauth
SITE_ID = 1
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary / Media storage settings
import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='').strip()
CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY', default='').strip()
CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET', default='').strip()

USE_CLOUDINARY_STORAGE = all([
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
])

if USE_CLOUDINARY_STORAGE:
    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET,
    )
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
    }
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

# Payment Settings
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')

STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')

# Admin credentials and payment destination
ADMIN_EMAIL = config('ADMIN_EMAIL', default='')
ADMIN_PASSWORD = config('ADMIN_PASSWORD', default='')
ADMIN_UPI_ID = config('ADMIN_UPI_ID', default='')
ALLOW_ENV_ADMIN_SYNC = DEBUG and _to_bool(config('ALLOW_ENV_ADMIN_SYNC', default='False'), default=False)

# Redis Configuration
CELERY_BROKER_URL = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('REDIS_URL', default='redis://localhost:6379/0')

# Security Settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = _to_bool(config('USE_X_FORWARDED_HOST', default='True' if not DEBUG else 'False'), default=not DEBUG)
SECURE_SSL_REDIRECT = _to_bool(config('SECURE_SSL_REDIRECT', default='True' if not DEBUG else 'False'), default=not DEBUG)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=(31536000 if not DEBUG else 0), cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _to_bool(
    config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default='True' if not DEBUG else 'False'),
    default=not DEBUG
)
SECURE_HSTS_PRELOAD = _to_bool(
    config('SECURE_HSTS_PRELOAD', default='True' if not DEBUG else 'False'),
    default=not DEBUG
)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

SESSION_COOKIE_SECURE = _to_bool(config('SESSION_COOKIE_SECURE', default='True' if not DEBUG else 'False'), default=not DEBUG)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default='Lax')

CSRF_COOKIE_SECURE = _to_bool(config('CSRF_COOKIE_SECURE', default='True' if not DEBUG else 'False'), default=not DEBUG)
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = config('CSRF_COOKIE_SAMESITE', default='Lax' if DEBUG else 'Strict')

if IS_PRODUCTION:
    # Enforce secure defaults in production even if environment values are lax.
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = max(SECURE_HSTS_SECONDS, 31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Enable only when local preview tooling truly needs dynamic CSRF host injection.
ALLOW_DYNAMIC_CSRF_ORIGINS = DEBUG and _to_bool(config('ALLOW_DYNAMIC_CSRF_ORIGINS', default='False'), default=False)

# CORS Settings
_default_origins = 'http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000'
CORS_ALLOWED_ORIGINS = _csv_to_list(config('CORS_ALLOWED_ORIGINS', default=_default_origins))
CORS_ALLOW_CREDENTIALS = _to_bool(config('CORS_ALLOW_CREDENTIALS', default='True'), default=True)
CORS_ALLOW_ALL_ORIGINS = DEBUG and _to_bool(config('CORS_ALLOW_ALL_ORIGINS', default='False'), default=False)
if CORS_ALLOW_ALL_ORIGINS and CORS_ALLOW_CREDENTIALS:
    CORS_ALLOW_CREDENTIALS = False

# CSRF Settings - Secure but functional for development
CSRF_TRUSTED_ORIGINS = _csv_to_list(config('CSRF_TRUSTED_ORIGINS', default=_default_origins))

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# Custom Settings
COMMISSION_RATE = config('COMMISSION_RATE', default=0.10, cast=float)  # 10% commission
SHIPPING_COST = config('SHIPPING_COST', default=50, cast=float)
TAX_RATE = config('TAX_RATE', default=0.18, cast=float)  # 18% GST

# Frontend URL for email verification and password reset
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

