# Generated by Django 6.0.2 on 2026-02-05 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('business_name', models.CharField(max_length=200, verbose_name='business name')),
                ('business_description', models.TextField(max_length=1000, verbose_name='business description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sellers/logos/', verbose_name='business logo')),
                ('business_type', models.CharField(default='individual', max_length=50, verbose_name='business type')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='registration number')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='tax ID')),
                ('business_email', models.EmailField(blank=True, max_length=254, verbose_name='business email')),
                ('business_phone', models.CharField(blank=True, max_length=20, verbose_name='business phone')),
                ('business_website', models.URLField(blank=True, verbose_name='business website')),
                ('business_address', models.TextField(blank=True, verbose_name='business address')),
                ('business_city', models.CharField(blank=True, max_length=100, verbose_name='business city')),
                ('business_state', models.CharField(blank=True, max_length=100, verbose_name='business state')),
                ('business_country', models.CharField(blank=True, max_length=100, verbose_name='business country')),
                ('business_postal_code', models.CharField(blank=True, max_length=20, verbose_name='business postal code')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20, verbose_name='approval status')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('bank_account_name', models.CharField(blank=True, max_length=200, verbose_name='bank account name')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='bank account number')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='bank name')),
                ('bank_branch', models.CharField(blank=True, max_length=200, verbose_name='bank branch')),
                ('ifsc_code', models.CharField(blank=True, max_length=20, verbose_name='IFSC code')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='total sales')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='total orders')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='average rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='total reviews')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='commission rate')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured seller')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sellers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('document_type', models.CharField(choices=[('business_registration', 'Business Registration'), ('tax_certificate', 'Tax Certificate'), ('identity_proof', 'Identity Proof'), ('address_proof', 'Address Proof'), ('bank_statement', 'Bank Statement'), ('other', 'Other')], max_length=50, verbose_name='document type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('file', models.FileField(upload_to='sellers/documents/', verbose_name='file')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verification_notes', models.TextField(blank=True, verbose_name='verification notes')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Seller Document',
                'verbose_name_plural': 'Seller Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='amount')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='transaction ID')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Seller Payout',
                'verbose_name_plural': 'Seller Payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerEarnings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='date')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='total sales')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='total orders')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='commission amount')),
                ('net_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='net earnings')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Seller Earnings',
                'verbose_name_plural': 'Seller Earnings',
                'ordering': ['-date'],
                'unique_together': {('seller', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='rating')),
                ('comment', models.TextField(max_length=1000, verbose_name='comment')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='verified purchase')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews', to='sellers.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_seller_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Review',
                'verbose_name_plural': 'Seller Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('seller', 'user')},
            },
        ),
    ]
