# Generated by Django 6.0.2 on 2026-02-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cod_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_upi_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
