# Generated by Django 6.0.2 on 2026-02-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_create_seller_category'),
        ('products', '0002_product_cod_available_product_seller_upi_id'),
    ]

    operations = [
    ]
