# Generated by Django 6.0.2 on 2026-02-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20260215_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cod_available',
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_upi_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
